export {default as App} from './app/app';
export {default as Main} from './main/main'
export {default as Channel} from './channel/channel';
export {default as Search} from './Search/search'
export {default as VideoDetail} from './video-detail/videoDetail'
export {default as Navbar} from './navbar/navbar';
export {default as SearchBar} from './search-bar/SearchBar'
export {default as Category} from './category/Category'
export {default as Videos} from './videos/Videos'
export {default as Videocard} from './video-card/Videocard'
export {default as Channelcard} from './channel-card/Channelcard'
export {default as Loader} from './loader/Loader'